name: ml_data_provider
author: fetchai
version: 0.27.2
type: skill
description: The ml data provider skill implements a provider for Machine Learning
  datasets in order to monetize data.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmYBr97UhQA8GoWFN6yNKdWix1AKJYx4zY246HYAFGpYRP
  __init__.py: QmeiKVXdPPR7w3uiaAtAAnZFVYC9khKdLACFoT5nssGudx
  behaviours.py: QmU6DnhfLsYNGoJMrW9jeQ9CknpJG5cp2WjCFwPQfuJkiV
  dialogues.py: QmTWTeidShLf6Pg5pxrYTxAFMYWQ5rRdgLrXLcXMJS8vYn
  handlers.py: Qmda9SU3rhoMQFiWFfpFRJ9dEwDtqopsYFGnNFydRrQ8ms
  strategy.py: QmVbxMMFCzwdJKf4Toyfd4Qpqn9tMVy4x4JVUqc6GEPYzb
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols:
- fetchai/default:1.1.2
- fetchai/ledger_api:1.1.2
- fetchai/ml_trade:1.1.2
- fetchai/oef_search:1.1.2
skills:
- fetchai/generic_seller:0.28.2
behaviours:
  service_registration:
    args:
      services_interval: 20
    class_name: ServiceRegistrationBehaviour
handlers:
  ledger_api:
    args: {}
    class_name: LedgerApiHandler
  ml_trade:
    args: {}
    class_name: MlTradeHandler
  oef_search:
    args: {}
    class_name: OefSearchHandler
models:
  default_dialogues:
    args: {}
    class_name: DefaultDialogues
  ledger_api_dialogues:
    args: {}
    class_name: LedgerApiDialogues
  ml_trade_dialogues:
    args: {}
    class_name: MlTradeDialogues
  oef_search_dialogues:
    args: {}
    class_name: OefSearchDialogues
  strategy:
    args:
      batch_size: 2
      buyer_tx_fee: 1550000000000000
      classification:
        piece: classification
        value: seller
      is_ledger_tx: true
      location:
        latitude: 51.5194
        longitude: 0.127
      personality_data:
        piece: genus
        value: data
      price_per_data_batch: 100
      seller_tx_fee: 0
      service_data:
        key: dataset_id
        value: fmnist
      service_id: data_service
    class_name: Strategy
dependencies:
  numpy: {}
  tensorflow:
    version: <3.0.0,>=2.4.0
is_abstract: false
