name: 'ml_data_provider'
author: fetchai
version: 0.1.0
license: Apache-2.0
fingerprint: ""
description: "The ml data provider skill implements a provider for Machine Learning datasets in order to monetize data."
behaviours:
  service_registration:
    class_name: ServiceRegistrationBehaviour
    args:
      services_interval: 30
handlers:
  ml_trade:
    class_name: MLTradeHandler
    args: {}
models:
  strategy:
    class_name: Strategy
    args:
      price_per_data_batch: 100
      batch_size: 2
      seller_tx_fee: 0
      buyer_tx_fee: 10
      dataset_id: 'fmnist'
      currency_id: 'FET'
      ledger_id: 'fetchai'
      is_ledger_tx: False
protocols: ['fetchai/oef_search:0.1.0', 'fetchai/ml_trade:0.1.0']
dependencies:
  tensorflow: { version: "==1.14.0" }
  numpy: {}
