name: ml_data_provider
author: fetchai
version: 0.27.6
type: skill
description: The ml data provider skill implements a provider for Machine Learning
  datasets in order to monetize data.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmcPsTwjWbUTMamK8aH94yRgYrKrmCwzffmMUueLya5wAg
  __init__.py: QmcknNVN92YuDs73HveMKx5Dkr6JCxHfzeF7ywX3tSRakX
  behaviours.py: QmZvLViapWxG1H41wn4e6Mzt8nmV6yyuk2sSsLJKZTQy2c
  dialogues.py: QmaVve3Ldt3TN1QSA1x58tBruPDRZ5bnVYHencsVHvfsoh
  handlers.py: QmYkHwQSjJh7CsMDRscidGzn4DMcWTJrFYMhV9yVaGNFZF
  strategy.py: QmW8SBVyZyfpQG4b25xvjtEQVuKNPbqryYLdMVzkjtYFxc
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols:
- fetchai/default:1.1.7
- fetchai/ledger_api:1.1.7
- fetchai/ml_trade:1.1.7
- fetchai/oef_search:1.1.7
skills:
- fetchai/generic_seller:0.28.6
behaviours:
  service_registration:
    args:
      services_interval: 20
    class_name: ServiceRegistrationBehaviour
handlers:
  ledger_api:
    args: {}
    class_name: LedgerApiHandler
  ml_trade:
    args: {}
    class_name: MlTradeHandler
  oef_search:
    args: {}
    class_name: OefSearchHandler
models:
  default_dialogues:
    args: {}
    class_name: DefaultDialogues
  ledger_api_dialogues:
    args: {}
    class_name: LedgerApiDialogues
  ml_trade_dialogues:
    args: {}
    class_name: MlTradeDialogues
  oef_search_dialogues:
    args: {}
    class_name: OefSearchDialogues
  strategy:
    args:
      batch_size: 2
      buyer_tx_fee: 1550000000000000
      classification:
        piece: classification
        value: seller
      is_ledger_tx: true
      location:
        latitude: 51.5194
        longitude: 0.127
      personality_data:
        piece: genus
        value: data
      price_per_data_batch: 100
      seller_tx_fee: 0
      service_data:
        key: dataset_id
        value: fmnist
      service_id: data_service
    class_name: Strategy
dependencies:
  numpy: {}
  tensorflow:
    version: <3.0.0,>=2.4.0
is_abstract: false
