name: ml_data_provider
author: fetchai
version: 0.20.0
type: skill
description: The ml data provider skill implements a provider for Machine Learning
  datasets in order to monetize data.
license: Apache-2.0
aea_version: '>=0.11.0, <0.12.0'
fingerprint:
  README.md: QmYBr97UhQA8GoWFN6yNKdWix1AKJYx4zY246HYAFGpYRP
  __init__.py: QmWyEPtYQUrEfuUK6R6q43gc232TBpPcrUHo4QqFYc9SBk
  behaviours.py: QmWgXU9qgahXwMKNqLLfDiGNYJozSXv2SVMkoPDQncC7ok
  dialogues.py: QmdNfb5f2bqTVTqk3DPRnwbyGDyeYgw7XgT339csLSrZdn
  handlers.py: QmWCVSnLMSLLPB9koJVc7g12YsfW3eCgkMET8TTpwDDW69
  strategy.py: Qmf6gMbMXMCBAmYkXfrcj6GvztaQHUMuRv6ujHQUmXtCE6
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols:
- fetchai/default:0.13.0
- fetchai/ledger_api:0.11.0
- fetchai/ml_trade:0.13.0
- fetchai/oef_search:0.14.0
skills:
- fetchai/generic_seller:0.21.0
behaviours:
  service_registration:
    args:
      services_interval: 20
    class_name: ServiceRegistrationBehaviour
handlers:
  ledger_api:
    args: {}
    class_name: LedgerApiHandler
  ml_trade:
    args: {}
    class_name: MlTradeHandler
  oef_search:
    args: {}
    class_name: OefSearchHandler
models:
  default_dialogues:
    args: {}
    class_name: DefaultDialogues
  ledger_api_dialogues:
    args: {}
    class_name: LedgerApiDialogues
  ml_trade_dialogues:
    args: {}
    class_name: MlTradeDialogues
  oef_search_dialogues:
    args: {}
    class_name: OefSearchDialogues
  strategy:
    args:
      batch_size: 2
      buyer_tx_fee: 10
      classification:
        piece: classification
        value: seller
      is_ledger_tx: true
      location:
        latitude: 51.5194
        longitude: 0.127
      personality_data:
        piece: genus
        value: data
      price_per_data_batch: 100
      seller_tx_fee: 0
      service_data:
        key: dataset_id
        value: fmnist
      service_id: data_service
    class_name: Strategy
dependencies:
  numpy: {}
  tensorflow:
    version: ~=2.4.0
is_abstract: false
