# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocols/gym/gym.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="protocols/gym/gym.proto",
    package="fetch.aea.Gym",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x17protocols/gym/gym.proto\x12\rfetch.aea.Gym"\xdb\x04\n\nGymMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x12"\n\x1a\x64ialogue_starter_reference\x18\x02 \x01(\t\x12$\n\x1c\x64ialogue_responder_reference\x18\x03 \x01(\t\x12\x0e\n\x06target\x18\x04 \x01(\x05\x12,\n\x03\x61\x63t\x18\x05 \x01(\x0b\x32\x1d.fetch.aea.Gym.GymMessage.ActH\x00\x12\x30\n\x05\x63lose\x18\x06 \x01(\x0b\x32\x1f.fetch.aea.Gym.GymMessage.CloseH\x00\x12\x34\n\x07percept\x18\x07 \x01(\x0b\x32!.fetch.aea.Gym.GymMessage.PerceptH\x00\x12\x30\n\x05reset\x18\x08 \x01(\x0b\x32\x1f.fetch.aea.Gym.GymMessage.ResetH\x00\x1a\x12\n\x03\x41ny\x12\x0b\n\x03\x61ny\x18\x01 \x01(\x0c\x1a\x45\n\x03\x41\x63t\x12-\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x1d.fetch.aea.Gym.GymMessage.Any\x12\x0f\n\x07step_id\x18\x02 \x01(\x05\x1a\x99\x01\n\x07Percept\x12\x0f\n\x07step_id\x18\x01 \x01(\x05\x12\x32\n\x0bobservation\x18\x02 \x01(\x0b\x32\x1d.fetch.aea.Gym.GymMessage.Any\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x12+\n\x04info\x18\x05 \x01(\x0b\x32\x1d.fetch.aea.Gym.GymMessage.Any\x1a\x07\n\x05Reset\x1a\x07\n\x05\x43loseB\x0e\n\x0cperformativeb\x06proto3'
    ),
)


_GYMMESSAGE_ANY = _descriptor.Descriptor(
    name="Any",
    full_name="fetch.aea.Gym.GymMessage.Any",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="any",
            full_name="fetch.aea.Gym.GymMessage.Any.any",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=367,
    serialized_end=385,
)

_GYMMESSAGE_ACT = _descriptor.Descriptor(
    name="Act",
    full_name="fetch.aea.Gym.GymMessage.Act",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="action",
            full_name="fetch.aea.Gym.GymMessage.Act.action",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="step_id",
            full_name="fetch.aea.Gym.GymMessage.Act.step_id",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=387,
    serialized_end=456,
)

_GYMMESSAGE_PERCEPT = _descriptor.Descriptor(
    name="Percept",
    full_name="fetch.aea.Gym.GymMessage.Percept",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="step_id",
            full_name="fetch.aea.Gym.GymMessage.Percept.step_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="observation",
            full_name="fetch.aea.Gym.GymMessage.Percept.observation",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reward",
            full_name="fetch.aea.Gym.GymMessage.Percept.reward",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="done",
            full_name="fetch.aea.Gym.GymMessage.Percept.done",
            index=3,
            number=4,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="info",
            full_name="fetch.aea.Gym.GymMessage.Percept.info",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=459,
    serialized_end=612,
)

_GYMMESSAGE_RESET = _descriptor.Descriptor(
    name="Reset",
    full_name="fetch.aea.Gym.GymMessage.Reset",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=614,
    serialized_end=621,
)

_GYMMESSAGE_CLOSE = _descriptor.Descriptor(
    name="Close",
    full_name="fetch.aea.Gym.GymMessage.Close",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=623,
    serialized_end=630,
)

_GYMMESSAGE = _descriptor.Descriptor(
    name="GymMessage",
    full_name="fetch.aea.Gym.GymMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="message_id",
            full_name="fetch.aea.Gym.GymMessage.message_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dialogue_starter_reference",
            full_name="fetch.aea.Gym.GymMessage.dialogue_starter_reference",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="dialogue_responder_reference",
            full_name="fetch.aea.Gym.GymMessage.dialogue_responder_reference",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="target",
            full_name="fetch.aea.Gym.GymMessage.target",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="act",
            full_name="fetch.aea.Gym.GymMessage.act",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="close",
            full_name="fetch.aea.Gym.GymMessage.close",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="percept",
            full_name="fetch.aea.Gym.GymMessage.percept",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reset",
            full_name="fetch.aea.Gym.GymMessage.reset",
            index=7,
            number=8,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _GYMMESSAGE_ANY,
        _GYMMESSAGE_ACT,
        _GYMMESSAGE_PERCEPT,
        _GYMMESSAGE_RESET,
        _GYMMESSAGE_CLOSE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="fetch.aea.Gym.GymMessage.performative",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=43,
    serialized_end=646,
)

_GYMMESSAGE_ANY.containing_type = _GYMMESSAGE
_GYMMESSAGE_ACT.fields_by_name["action"].message_type = _GYMMESSAGE_ANY
_GYMMESSAGE_ACT.containing_type = _GYMMESSAGE
_GYMMESSAGE_PERCEPT.fields_by_name["observation"].message_type = _GYMMESSAGE_ANY
_GYMMESSAGE_PERCEPT.fields_by_name["info"].message_type = _GYMMESSAGE_ANY
_GYMMESSAGE_PERCEPT.containing_type = _GYMMESSAGE
_GYMMESSAGE_RESET.containing_type = _GYMMESSAGE
_GYMMESSAGE_CLOSE.containing_type = _GYMMESSAGE
_GYMMESSAGE.fields_by_name["act"].message_type = _GYMMESSAGE_ACT
_GYMMESSAGE.fields_by_name["close"].message_type = _GYMMESSAGE_CLOSE
_GYMMESSAGE.fields_by_name["percept"].message_type = _GYMMESSAGE_PERCEPT
_GYMMESSAGE.fields_by_name["reset"].message_type = _GYMMESSAGE_RESET
_GYMMESSAGE.oneofs_by_name["performative"].fields.append(
    _GYMMESSAGE.fields_by_name["act"]
)
_GYMMESSAGE.fields_by_name["act"].containing_oneof = _GYMMESSAGE.oneofs_by_name[
    "performative"
]
_GYMMESSAGE.oneofs_by_name["performative"].fields.append(
    _GYMMESSAGE.fields_by_name["close"]
)
_GYMMESSAGE.fields_by_name["close"].containing_oneof = _GYMMESSAGE.oneofs_by_name[
    "performative"
]
_GYMMESSAGE.oneofs_by_name["performative"].fields.append(
    _GYMMESSAGE.fields_by_name["percept"]
)
_GYMMESSAGE.fields_by_name["percept"].containing_oneof = _GYMMESSAGE.oneofs_by_name[
    "performative"
]
_GYMMESSAGE.oneofs_by_name["performative"].fields.append(
    _GYMMESSAGE.fields_by_name["reset"]
)
_GYMMESSAGE.fields_by_name["reset"].containing_oneof = _GYMMESSAGE.oneofs_by_name[
    "performative"
]
DESCRIPTOR.message_types_by_name["GymMessage"] = _GYMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GymMessage = _reflection.GeneratedProtocolMessageType(
    "GymMessage",
    (_message.Message,),
    dict(
        Any=_reflection.GeneratedProtocolMessageType(
            "Any",
            (_message.Message,),
            dict(
                DESCRIPTOR=_GYMMESSAGE_ANY,
                __module__="protocols.gym.gym_pb2"
                # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage.Any)
            ),
        ),
        Act=_reflection.GeneratedProtocolMessageType(
            "Act",
            (_message.Message,),
            dict(
                DESCRIPTOR=_GYMMESSAGE_ACT,
                __module__="protocols.gym.gym_pb2"
                # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage.Act)
            ),
        ),
        Percept=_reflection.GeneratedProtocolMessageType(
            "Percept",
            (_message.Message,),
            dict(
                DESCRIPTOR=_GYMMESSAGE_PERCEPT,
                __module__="protocols.gym.gym_pb2"
                # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage.Percept)
            ),
        ),
        Reset=_reflection.GeneratedProtocolMessageType(
            "Reset",
            (_message.Message,),
            dict(
                DESCRIPTOR=_GYMMESSAGE_RESET,
                __module__="protocols.gym.gym_pb2"
                # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage.Reset)
            ),
        ),
        Close=_reflection.GeneratedProtocolMessageType(
            "Close",
            (_message.Message,),
            dict(
                DESCRIPTOR=_GYMMESSAGE_CLOSE,
                __module__="protocols.gym.gym_pb2"
                # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage.Close)
            ),
        ),
        DESCRIPTOR=_GYMMESSAGE,
        __module__="protocols.gym.gym_pb2"
        # @@protoc_insertion_point(class_scope:fetch.aea.Gym.GymMessage)
    ),
)
_sym_db.RegisterMessage(GymMessage)
_sym_db.RegisterMessage(GymMessage.Any)
_sym_db.RegisterMessage(GymMessage.Act)
_sym_db.RegisterMessage(GymMessage.Percept)
_sym_db.RegisterMessage(GymMessage.Reset)
_sym_db.RegisterMessage(GymMessage.Close)


# @@protoc_insertion_point(module_scope)
