name: 🐛 Bug Report
description: Report a reproducible bug.
title: "<Short bug description>"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue you are facing. Please complete the following so we can have the details necessary to assist you.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a new issue
      options:
        - label: I am running the [latest version of the AEA Framework](https://docs.fetch.ai/aea/version/).
          required: true
        - label: I checked the [documentation](https://docs.fetch.ai/aea/) and found no answer to my problem.
          required: true
        - label: I checked the [existing issues](https://github.com/fetchai/agents-aea/issues) to make sure my problem has not already been reported.
          required: true
        - label: I have read the [code of conduct](https://github.com/fetchai/agents-aea/blob/main/CODE_OF_CONDUCT.md) before creating this issue.
          required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe the behavior you are expecting
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Current Behavior
      description: Describe the current behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Detailed steps for reproducing the issue
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant information about your setup (this is important in case the issue is not reproducible except under certain conditions)
      placeholder: |
        Operating system [e.g. MacOS], Python version [e.g. 3.8.5], AEA version [e.g. 1.2.0], ...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Failure Logs
      description: Include any relevant log snippets or files here
    validations:
      required: false
