{{- range $key, $spec := .Values }}
{{- if eq $key "acnnodes" }}
{{- if $spec.enabled }}
{{- range $spec.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: node-priv-key-{{ .p2pport }}
type: Opaque
data:
  priv-key: {{ .privkey }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
