# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="consensus.proto",
    package="aea.fetchai.consensus",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x0f\x63onsensus.proto\x12\x15\x61\x65\x61.fetchai.consensus"\x92\x03\n\x10\x43onsensusMessage\x12W\n\x0b\x61ggregation\x18\x05 \x01(\x0b\x32@.aea.fetchai.consensus.ConsensusMessage.Aggregation_PerformativeH\x00\x12W\n\x0bobservation\x18\x06 \x01(\x0b\x32@.aea.fetchai.consensus.ConsensusMessage.Observation_PerformativeH\x00\x1aZ\n\x18Observation_Performative\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\x1a`\n\x18\x41ggregation_Performative\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x14\n\x0c\x63ontributors\x18\x03 \x03(\x05\x12\x11\n\tsignature\x18\x04 \x01(\tB\x0e\n\x0cperformativeb\x06proto3',
)


_CONSENSUSMESSAGE_OBSERVATION_PERFORMATIVE = _descriptor.Descriptor(
    name="Observation_Performative",
    full_name="aea.fetchai.consensus.ConsensusMessage.Observation_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.fetchai.consensus.ConsensusMessage.Observation_Performative.value",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="time",
            full_name="aea.fetchai.consensus.ConsensusMessage.Observation_Performative.time",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="source",
            full_name="aea.fetchai.consensus.ConsensusMessage.Observation_Performative.source",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="aea.fetchai.consensus.ConsensusMessage.Observation_Performative.signature",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=241,
    serialized_end=331,
)

_CONSENSUSMESSAGE_AGGREGATION_PERFORMATIVE = _descriptor.Descriptor(
    name="Aggregation_Performative",
    full_name="aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative.value",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="time",
            full_name="aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative.time",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="contributors",
            full_name="aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative.contributors",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative.signature",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=333,
    serialized_end=429,
)

_CONSENSUSMESSAGE = _descriptor.Descriptor(
    name="ConsensusMessage",
    full_name="aea.fetchai.consensus.ConsensusMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="aggregation",
            full_name="aea.fetchai.consensus.ConsensusMessage.aggregation",
            index=0,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="observation",
            full_name="aea.fetchai.consensus.ConsensusMessage.observation",
            index=1,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _CONSENSUSMESSAGE_OBSERVATION_PERFORMATIVE,
        _CONSENSUSMESSAGE_AGGREGATION_PERFORMATIVE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="aea.fetchai.consensus.ConsensusMessage.performative",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=43,
    serialized_end=445,
)

_CONSENSUSMESSAGE_OBSERVATION_PERFORMATIVE.containing_type = _CONSENSUSMESSAGE
_CONSENSUSMESSAGE_AGGREGATION_PERFORMATIVE.containing_type = _CONSENSUSMESSAGE
_CONSENSUSMESSAGE.fields_by_name[
    "aggregation"
].message_type = _CONSENSUSMESSAGE_AGGREGATION_PERFORMATIVE
_CONSENSUSMESSAGE.fields_by_name[
    "observation"
].message_type = _CONSENSUSMESSAGE_OBSERVATION_PERFORMATIVE
_CONSENSUSMESSAGE.oneofs_by_name["performative"].fields.append(
    _CONSENSUSMESSAGE.fields_by_name["aggregation"]
)
_CONSENSUSMESSAGE.fields_by_name[
    "aggregation"
].containing_oneof = _CONSENSUSMESSAGE.oneofs_by_name["performative"]
_CONSENSUSMESSAGE.oneofs_by_name["performative"].fields.append(
    _CONSENSUSMESSAGE.fields_by_name["observation"]
)
_CONSENSUSMESSAGE.fields_by_name[
    "observation"
].containing_oneof = _CONSENSUSMESSAGE.oneofs_by_name["performative"]
DESCRIPTOR.message_types_by_name["ConsensusMessage"] = _CONSENSUSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsensusMessage = _reflection.GeneratedProtocolMessageType(
    "ConsensusMessage",
    (_message.Message,),
    {
        "Observation_Performative": _reflection.GeneratedProtocolMessageType(
            "Observation_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _CONSENSUSMESSAGE_OBSERVATION_PERFORMATIVE,
                "__module__": "consensus_pb2"
                # @@protoc_insertion_point(class_scope:aea.fetchai.consensus.ConsensusMessage.Observation_Performative)
            },
        ),
        "Aggregation_Performative": _reflection.GeneratedProtocolMessageType(
            "Aggregation_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _CONSENSUSMESSAGE_AGGREGATION_PERFORMATIVE,
                "__module__": "consensus_pb2"
                # @@protoc_insertion_point(class_scope:aea.fetchai.consensus.ConsensusMessage.Aggregation_Performative)
            },
        ),
        "DESCRIPTOR": _CONSENSUSMESSAGE,
        "__module__": "consensus_pb2"
        # @@protoc_insertion_point(class_scope:aea.fetchai.consensus.ConsensusMessage)
    },
)
_sym_db.RegisterMessage(ConsensusMessage)
_sym_db.RegisterMessage(ConsensusMessage.Observation_Performative)
_sym_db.RegisterMessage(ConsensusMessage.Aggregation_Performative)


# @@protoc_insertion_point(module_scope)
