# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x61ggregation.proto\x12\x1e\x61\x65\x61.fetchai.aggregation.v0_2_1"\xaa\x03\n\x12\x41ggregationMessage\x12\x62\n\x0b\x61ggregation\x18\x05 \x01(\x0b\x32K.aea.fetchai.aggregation.v0_2_1.AggregationMessage.Aggregation_PerformativeH\x00\x12\x62\n\x0bobservation\x18\x06 \x01(\x0b\x32K.aea.fetchai.aggregation.v0_2_1.AggregationMessage.Observation_PerformativeH\x00\x1aZ\n\x18Observation_Performative\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\x1a`\n\x18\x41ggregation_Performative\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontributors\x18\x03 \x03(\t\x12\x11\n\tsignature\x18\x04 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)


_AGGREGATIONMESSAGE = DESCRIPTOR.message_types_by_name["AggregationMessage"]
_AGGREGATIONMESSAGE_OBSERVATION_PERFORMATIVE = _AGGREGATIONMESSAGE.nested_types_by_name[
    "Observation_Performative"
]
_AGGREGATIONMESSAGE_AGGREGATION_PERFORMATIVE = _AGGREGATIONMESSAGE.nested_types_by_name[
    "Aggregation_Performative"
]
AggregationMessage = _reflection.GeneratedProtocolMessageType(
    "AggregationMessage",
    (_message.Message,),
    {
        "Observation_Performative": _reflection.GeneratedProtocolMessageType(
            "Observation_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGGREGATIONMESSAGE_OBSERVATION_PERFORMATIVE,
                "__module__": "aggregation_pb2"
                # @@protoc_insertion_point(class_scope:aea.fetchai.aggregation.v0_2_1.AggregationMessage.Observation_Performative)
            },
        ),
        "Aggregation_Performative": _reflection.GeneratedProtocolMessageType(
            "Aggregation_Performative",
            (_message.Message,),
            {
                "DESCRIPTOR": _AGGREGATIONMESSAGE_AGGREGATION_PERFORMATIVE,
                "__module__": "aggregation_pb2"
                # @@protoc_insertion_point(class_scope:aea.fetchai.aggregation.v0_2_1.AggregationMessage.Aggregation_Performative)
            },
        ),
        "DESCRIPTOR": _AGGREGATIONMESSAGE,
        "__module__": "aggregation_pb2"
        # @@protoc_insertion_point(class_scope:aea.fetchai.aggregation.v0_2_1.AggregationMessage)
    },
)
_sym_db.RegisterMessage(AggregationMessage)
_sym_db.RegisterMessage(AggregationMessage.Observation_Performative)
_sym_db.RegisterMessage(AggregationMessage.Aggregation_Performative)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _AGGREGATIONMESSAGE._serialized_start = 54
    _AGGREGATIONMESSAGE._serialized_end = 480
    _AGGREGATIONMESSAGE_OBSERVATION_PERFORMATIVE._serialized_start = 276
    _AGGREGATIONMESSAGE_OBSERVATION_PERFORMATIVE._serialized_end = 366
    _AGGREGATIONMESSAGE_AGGREGATION_PERFORMATIVE._serialized_start = 368
    _AGGREGATIONMESSAGE_AGGREGATION_PERFORMATIVE._serialized_end = 464
# @@protoc_insertion_point(module_scope)
